INSERT INTO Segment(Id, Name, Rate)
VALUES(1,'Varejo', 6.37),
	  (2,'Personnalite',3.47),
	  (3,'Private',0.87);
GO

INSERT INTO Country(Name,Currency) VALUES
('Afeganistão','AFN'),
('África do Sul','ZAR'),
('Albânia','ALL'),
('Argélia','DZD'),
('Alemanha','EUR'),
('Andorra','EUR'),
('Angola','AOA'),
('Anguilla','XCD'),
('Antígua e Barbuda','XCD'),
('Antilhas Holandesas','ANG'),
('Arábia Saudita','SAR'),
('Argentina','ARS'),
('Armênia','AMD'),
('Aruba','AWG'),
('Austrália','AUD'),
('Áustria','EUR'),
('Azerbaijão','AZN'),
('Bahamas','BSD'),
('Bahrain','BHD'),
('Bangladesh','BDT'),
('Barbados','BBD'),
('Belarus','BYR'),
('Bélgica','EUR'),
('Belize','BZD'),
('Benin','XOF'),
('Bermudas','BMD'),
('Butão','INR'),
('Bolívia','BOB'),
('Bósnia e Herzegovina','BAM'),
('Botswana','BWP'),
('Bouvet','NOK'),
('Brasil','BRL'),
('Brunei Darussalam','BND'),
('Bulgária','BGN'),
('Burkina Faso','XOF'),
('Burundi','BIF'),
('Ilhas Cayman','KYD'),
('Camboja','KHR'),
('Camarões','XAF'),
('Canadá','CAD'),
('Cabo Verde','CV'),
('República Centro-Africana','XAF'),
('Chile','CLP'),
('China','CNY'),
('Ilha Christmas','AUD'),
('Chipre','CYP'),
('Ilhas Cocos (Keeling)','AUD'),
('Colômbia','COP'),
('Comores','KMF'),
('Congo','XAF'),
('Congo','CDF'),
('Cook','NZD'),
('República da Coreia','KRW'),
('Coreia','KPW'),
('Costa Rica','CRC'),
('Costa do Marfim','XOF'),
('Croácia','HRK'),
('Cuba','CUP'),
('Dinamarca','DKK'),
('Djibouti','DJF'),
('República Dominicana','DOP'),
('Dominica','XCD'),
('Egito','EGP'),
('El Savador','SVC'),
('Emirados Árabes Unidos','AED'),
('Equador','USD'),
('Eritrea','ERN'),
('Espanha','EUR'),
('Estônia','EEK'),
('Estados Unidos','USD'),
('Etiópia','ETB'),
('Ilhas Falkland (Malvinas)','FKP'),
('Ilhas Faroé','DKK'),
('Fiji','FJD'),
('Finlândia','EUR'),
('Fundo Monetário Internacional (FMI)','XDR'),
('França','EUR'),
('Gabão','XAF'),
('Gâmbia','GMD'),
('Ilhas Geórgia do Sul e Sandwich do Sul','GEL'),
('Gana','GHS'),
('Gibraltar','GIP'),
('Grécia','EUR'),
('granada','XCD'),
('Groenlândia','DKK'),
('Guadalupe','EUR'),
('Guam','USD'),
('Guatemala','GTQ'),
('Guiné','GNF'),
('Guiné-Bissau','GWP'),
('Guiné Equatorial','XAF'),
('Guiana','GYD'),
('Guiana Francesa','EUR'),
('Haiti','HTG'),
('Ilhas Heard e Mcdonald','AUD'),
('Honduras','LST'),
('Hong Kong','HKD'),
('Hungria','HUF'),
('Ilhas Menores Distantes dos Estados Unidos','USD'),
('Ilhas Virgens Britânicas','USD'),
('Ilhas Virgens (EUA)','USD'),
('Índia','INR'),
('Indonésia','IDR'),
('Irã (República Islâmica do)','IRR'),
('Iraque','IQD'),
('Irlanda','EUR'),
('Islândia','ISK'),
('Israel','ELES'),
('Itália','EUR'),
('Jamaica','JMD'),
('Japão','JPY'),
('Jordânia','JOD'),
('Cazaquistão','KZT'),
('Quênia','KES'),
('Quirguistão','KGS'),
('kiribati','AUD'),
('Kuweit','KWD'),
('Laos','LAK'),
('Lesoto','ZAR'),
('Látvia','LVL'),
('Líbano','LBP'),
('Libéria','LRD'),
('Jamahiriya árabe da Líbia','LYD'),
('Liechtenstein','CHF'),
('Lituânia','LTL'),
('Luxemburgo','EUR'),
('Macau','MOP'),
('Macedônia','MKD'),
('Madagáscar','MGA'),
('Malásia','MYR'),
('Malavi','MWK'),
('Maldivas','MVR'),
('Mali','XOF'),
('Malta','MTL'),
('Ilhas Marianas do Norte','USD'),
('Marrocos','MAD'),
('Marshall','USD'),
('Martinique','EUR'),
('Mauritius','PAREDE'),
('Mauritânia','MRO'),
('Mayotte','EUR'),
('México','MXN'),
('Moldávia','MDL'),
('Monaco','EUR'),
('Mongólia','MNT'),
('Montenegro','EUR'),
('montserrat','XCD'),
('Moçambique','MZN'),
('Myanmar','MM'),
('Namíbia','ZAR'),
('nauru','AUD'),
('Nepal','NPR'),
('Nicarágua','NIO'),
('Níger','XOF'),
('Nigéria','NGN'),
('Niue','NZD'),
('Ilha Norfolk','AUD'),
('Noruega','NOK'),
('New Caledonia','XPF'),
('nova Zelândia','NZD'),
('Oceano Índico','USD'),
('Oman','OMR'),
('Uganda','UGX'),
('Uzbequistão','UZS'),
('Paquistão','PKR'),
('Palau','USD'),
('Panamá','PAB'),
('Papua Nova Guiné','PGK'),
('Paraguai','PYG'),
('Holanda','EUR'),
('Peru','PEN'),
('Filipinas','PHP'),
('pitcairn','NZD'),
('Polônia','PLN'),
('Polinésia Francesa','XPF'),
('Porto Rico','USD'),
('Portugal','EUR'),
('Catar','QAR'),
('reunião','EUR'),
('Romênia','RON'),
('Reino Unido','GBP'),
('Federação Russa','RUB'),
('Ruanda','RWF'),
('Saara Ocidental','MAD'),
('St. Helena','SHP'),
('St. Kitts and Nevis','XCD'),
('St. Lucia','XCD'),
('San Marino','EUR'),
('São Pedro e Miquelon','EUR'),
('St. Vincent e Granadinas','XCD'),
('Ilhas Salomão','SBD'),
('samoa','WST'),
('Samoa Americana','USD'),
('São Tomé e Príncipe','STD'),
('Senegal','XOF'),
('Sérvia','RSD'),
('seychelles','SCR'),
('Serra Leoa','SLL'),
('Cingapura','SGD'),
('Eslováquia','SKK'),
('Eslovenia','EUR'),
('Somália','SOS'),
('Sudão','SDG'),
('Sri Lanka','LKR'),
('camurça','SEK'),
('Suíça','CHF'),
('suriname','DTH'),
('Ilhas Svalbard e Jan Mayen','NOK'),
('Suazilândia','SZL'),
('República Árabe da Síria','SYP'),
('Tadjiquistão','TJS'),
('Taiwan','TWD'),
('Tanzânia','TZS'),
('Territórios Franceses do Sul','EUR'),
('Chade','XAF'),
('República Tcheca','CZK'),
('Tailândia','THB'),
('Timor Leste','USD'),
('Togo','XOF'),
('Tokelau','NZD'),
('tonga','TOP'),
('Trinidad e Tobago','TTD'),
('Tunísia','TND'),
('Turcomenistão','TMM'),
('Ilhas Turks e Caicos','USD'),
('tuvalu','AUD'),
('Ucrânia','UAH'),
('Uruguai','UYU'),
('Vanuatu','VUV'),
('Cidade do Vaticano Estado da Santa Sé','EUR'),
('Venezuela','VEF'),
('Vietnã','VND'),
('Wallis e Futuna','XPF'),
('Iémen','YER'),
('Zâmbia','Kwacha'),
('Zimbábue','ZWD')